
services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - networks
  nginx:
    image: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    networks:
      - networks
networks:
    networks: